/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicDeviceHeartbeatRouteImport } from './routes/api/public/device-heartbeat'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDeviceHeartbeatRoute =
  ApiPublicDeviceHeartbeatRouteImport.update({
    id: '/api/public/device-heartbeat',
    path: '/api/public/device-heartbeat',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/device-heartbeat': typeof ApiPublicDeviceHeartbeatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/device-heartbeat': typeof ApiPublicDeviceHeartbeatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/device-heartbeat': typeof ApiPublicDeviceHeartbeatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/device-heartbeat'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/device-heartbeat'
  id: '__root__' | '/' | '/api/public/device-heartbeat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicDeviceHeartbeatRoute: typeof ApiPublicDeviceHeartbeatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/device-heartbeat': {
      id: '/api/public/device-heartbeat'
      path: '/api/public/device-heartbeat'
      fullPath: '/api/public/device-heartbeat'
      preLoaderRoute: typeof ApiPublicDeviceHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicDeviceHeartbeatRoute: ApiPublicDeviceHeartbeatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
